name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run on"
        required: true
        default: "main"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update CNAME file
        run: echo "wiki.bruce.emericklaw.co.uk" > CNAME
      - name: Update mkdocs.yml site_url
        run: "sed -i 's|site_url: https://wiki.bruce.computer|site_url: https://github.emericklaw.co.uk/Bruce-Wiki|g' mkdocs.yml"
      - name: Deploy Preview Site
        run: mkdocs gh-deploy --force --verbose
